services:
  db:
    image: postgres:17
    restart: unless-stopped
    env_file:
      - ./.env.postgresql
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5454:5432"
    healthcheck: # Health check added here
      test: ["CMD-SHELL", "pg_isready -U tv-test-db-user -d task_view_test_db"]
      interval: 5s
      timeout: 5s
      retries: 5
  migration:
    image: gimanhead/taskview-db-migration:1.15.0
    restart: "no"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./.env.taskview
volumes:
  pgdata:
