services:
  db:
    image: postgres:17
    restart: unless-stopped
    env_file:
      - ./.env.postgresql
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck: # Health check added here
      test: ["CMD-SHELL", "pg_isready -U tvdbuser -d taskviewdb"]
      interval: 5s
      timeout: 5s
      retries: 5
  migration:
    image: gimanhead/taskview-ce-db-migration:1.18.0
    restart: "no"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./.env.taskview

  taskview-ce-webapp:
    image: gimanhead/taskview-ce-webapp:1.18.0
    restart: "no"
    ports:
      - "8888:80"
  taskview-api-server:
    image: gimanhead/taskview-ce-api-server:1.18.0
    restart: "no"
    ports:
      - "1725:1401"
    depends_on:
      db:
        condition: service_healthy
      migration:
        condition: service_completed_successfully
    env_file:
      - ./.env.taskview
    volumes:
      - ../postgresqlusr/log:/usr/src/app/logs
volumes:
  pgdata:
